[package]
name = "nng_sys"
version = "0.1.0"
authors = ["latsa <laca@gmx.us>"]
links = "nng"
build = "build.rs"

[lib]
name = "nng_sys"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
libc = "*"

[build-dependencies]
bindgen = "0.20.0"
cmake = "*"